java: Improve logging of undeclared TException
If a service handler throws an undeclared TException (for example,
missing the "throws" clause in the Frugal file), the generated processor
calls writeApplicationException, and then the exception is thrown to
FBaseProcessor and logged:

org.apache.thrift.TApplicationException: Internal error processing put: null
	at com.workiva.frugal.processor.FBaseProcessor.writeApplicationException(FBaseProcessor.java:114)
	at com.workiva.example.FExampleService$Processor.access$1200(FExampleService.java:183)
	at com.workiva.example.FExampleService$Processor$Put.process(FExampleService.java:288)
	at com.workiva.frugal.processor.FBaseProcessor.process(FBaseProcessor.java:52)
	at com.workiva.frugal.server.FNatsServer$Request.process(FNatsServer.java:320)
	at com.workiva.frugal.server.FNatsServer$Request.run(FNatsServer.java:310)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

This stack trace is unhelpful for diagnosing the problem, particularly
if the exception does not declare a message since it is logged as null.
Add initCause to the generated processor to improve the logged message:

org.apache.thrift.TApplicationException: Internal error processing put
	at com.workiva.frugal.processor.FBaseProcessor.writeApplicationException(FBaseProcessor.java:114)
	at com.workiva.example.FExampleService$Processor.access$1200(FXbrlMdkExampleService.java:183)
	at com.workiva.example.FExampleService$Processor$Put.process(FXbrlMdkExampleService.java:288)
	at com.workiva.frugal.processor.FBaseProcessor.process(FBaseProcessor.java:52)
	at com.workiva.frugal.server.FNatsServer$Request.process(FNatsServer.java:320)
	at com.workiva.frugal.server.FNatsServer$Request.run(FNatsServer.java:310)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.workiva.example.Undeclared
	at com.workiva.example.server.ExampleServiceHandler.put(ExampleServiceHandler.java:52)
	at com.workiva.example.FExampleService$Processor$Put.process(FXbrlMdkExampleService.java:277)
	... 8 common frames omitted