java: Include cause for HTTP timeout exception
The exception message for ConnectionTimeoutException and
SocketTimeoutException is quite similar, which makes it unclear whether
the connection failed or a read timed out:

org.apache.thrift.transport.TTransportException: http request timed out: Read timed out
	at com.workiva.frugal.transport.FHttpTransport.makeRequest(FHttpTransport.java:261)
	at com.workiva.frugal.transport.FHttpTransport.request(FHttpTransport.java:206)

Include the type of timeout in the message, and include the exception
cause in case those details would be useful.